version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/nginx.dockerfile
    links:
      - node1:node1
      - node2:node2
    ports:
      - "8080:8080"
    networks:
      - stbuilder-network
    volumes:
      - static-volume
      - media-volume
    depends_on:
      - node1
      - node2

  node1:
    container_name: app-1
    build:
      context: .
      dockerfile: ./web/stbuilder.dockerfile
    ports:
      - "8081"
    volumes:
      - static-volume
      - media-volume
    working_dir: /var/www/stbuilder
    networks:
      - stbuilder-network
    depends_on:
      - "db"

  node2:
    container_name: app-2
    build:
      context: .
      dockerfile: ./web/stbuilder.dockerfile
    ports:
      - "8081"
    volumes:
      - static-volume
      - media-volume
    working_dir: /var/www/stbuilder
    networks:
      - stbuilder-network
    depends_on:
      - "db"

  db:
    container_name: app-db
    image: postgres
    networks:
      - stbuilder-network

networks:
  stbuilder-network:
    driver: bridge

volumes:
  static-volume: ./web/static:/var/www/stbuilder/static
  media-volume: ./web/media:/var/www/stbuilder/media